/* COMMAND */
#define VSIO_OPEN "OPEN    "
#define VSIO_CLOSE "CLOSE   "
#define VSIO_READ "READ    "
#define VSIO_WRITE "WRITE   "
#define VSIO_REWRITE "REWRITE "
#define VSIO_DELETE "DELETE  "
#define VSIO_START_KEY_EQUAL "STARTEQ "
#define VSIO_START_KEY_NOTLESS "STARTGE "

/* ORGANIZATION */
#define VSIO_ESDS "ESDS"
#define VSIO_KSDS "KSDS"
#define VSIO_RRDS "RRDS"

/* ACCESS */
#define VSIO_SEQUENTIAL "SEQUENTIAL"
#define VSIO_DIRECT "DIRECT    "
#define VSIO_DYNAMIC "DYNAMIC   "

/* MODE */
#define VSIO_INPUT "INPUT "
#define VSIO_OUTPUT "OUTPUT"
#define VSIO_INPUT_OUTPUT "UPDATE"

/* */
#define VSIO_SUCCESS (0)
#define VSIO_LOGIC_ERROR (8)
#define VSIO_END_OF_FILE (9999)
#define VSIO_PARAMETER_ERROR (20..28)
#define VSIO_COMMAND_UNKNOWN (20)
#define VSIO_DATASET_ALREADY_OPEN (21)
#define VSIO_DATASET_NOT_OPEN (22)
#define VSIO_ORGANIZATION_KEYWORD (23)
#define VSIO_ACCESS_KEYWORD (24)
#define VSIO_ACCESS_UNSUPPORTED (25)
#define VSIO_MODE_KEYWORD (26)
#define VSIO_MODE_UNSUPPORTED (27)
#define VSIO_DDNAME_BLANK (28)
#define VSIO_DUPLICATE_RECORD (8)
#define VSIO_SEQUENCE_ERROR (12)
#define VSIO_RECORD_NOT_FOUND (16)
#define VSIO_NO_MORE_SPACE (28)
#define VSIO_READ_WITHOUT_START (88)
#define VSIO_FILE_OPEN "O"
#define VSIO_FILE_CLOSED "C"

typedef struct VSIO_PARAMETER_BLOCK
{
    char VSIO_COMMAND[8];
    int VSIO_RETURN_CODE;
    int VSIO_VSAM_RETURN_CODE;
    int VSIO_VSAM_FUNCTION_CODE;
    int VSIO_VSAM_FEEDBACK_CODE;
} VSIO_PARAMETER_BLOCK;

typedef struct VSIO_FILE_BLOCK
{
    char VSIO_DDNAME[8];
    char VSIO_ORGANIZATION[4];
    char VSIO_ACCESS[10];
    char VSIO_MODE[6];
    int VSIO_RECORD_LENGTH;
    int VSIO_KEY_POSITION;
    int VSIO_KEY_LENGTH;
    char VSIO_KEY_ARGUMENT;
    char BUFFER[153];
} VSIO_FILE_BLOCK;
