/* ---- Generated By SCRUPLES ----- */
/* ----- Fri Mar 11 10:31:00 2022 ----- */

      fssTxt(1, 2, 0X000030, "------------------------------- Utility Menu");
      fssFld(1, 47, 0X000030, "MSG1", 33, "");
      fssTxt(2, 2, 0X000030, "Option  ===>");
      fssFld(2, 15, 0X000000, "COMMAND", 65, "");
      fssTxt(4, 2, 0X000038, "  1");
      fssTxt(4, 6, 0X000030, "Browser           -");
      fssTxt(4, 26, 0X00F130, "DASD Dataset Browser");
      fssTxt(5, 2, 0X000038, "  S");
      fssTxt(5, 6, 0X000030, "System Stats      -");
      fssTxt(5, 26, 0X00F130, "System Status and Information");
      fssTxt(11, 2, 0X000030, "Hit");
      fssTxt(11, 6, 0X000038, "PF03/15");
      fssTxt(11, 14, 0X000030, "to terminate");


/* ----- End of Generated Code ----- */
